### ISSUE TITLE
Modeling Menu Controls

### ISSUE THREAD

**Issue by thePantz** [spelltwister/CodedUIFluentExtensions#11]
How would you model Menu controls?

For Example in Coded UI:
- WinMenuBars have root WinMenuItems. 
- When root WinMenuItems are selected they expand and show WinMenus containing more WinMenuItems
  - A WinMenuItem may contain a sub list of WinMenuItems
  - A WinMenuItem can be checked
  - A WinMenuItem can have a shortcut

So is the best approach to use INamedSelectionPageModel and create a custom list item, similar to your combobox implementation?

Any help is appreciated. 
Thanks

**Comment by spelltwister** [comment]
I don't have anything that would help with the shortcut key strokes to perform the action in terms of the interfaces available for page models.  It should be easy enough to create something that does that.

In terms of modeling a menu system I would follow the approach you have outlined, however, be careful of how you term 'selection'.  In the case of a menu item, since that is a system control, you do not need to test that 'selecting' or 'hovering' the item expands its children.  You can simply assume that works.

Further, the concept of 'selection' I have outlined in my I*Selection* types is more about permanent holding of the selected value, not the transient 'hover' type of selection.  It would apply for the 'checked' menu item, though.

I could imagine something like:

public interface IMenuPageModel
{
    IEnumerable<IMenuItemPageModel> Items {get;}
}

public interface IShortcutAccessible<TNextModel>
{
    TNextModel ActivateByShortcut();
}

public interface IMenuItemPageModel<TNextModel> : IMenuPageModel, IClickablePageModel<TNextModel>, ISelectablePageModel<TNextModel>, IShortcutAccessible<TNextModel>
{
    
}

public interface IFileMenu : IMenuPageModel
{
    IMenuItemPageModel Save {get; }
    IMenuItemPageModel SaveAs{ get; }
    IMenuItemPageModel RecentFiles {get;}
    IMenuItemPageModel Exit {get;}
}

public class FileMenuTests{
    private IFileMenu FileMenu {get;}
    public void SomeMenuTestMethod() {
        Assert.IsTrue(this.FileMenu.SaveAs.IsActionable(0));
        Assert.IsFalse(this.FileMenu.RecentFiles.Items.Any());
        // open a file here
        Assert.IsTrue(this.FileMenu.RecentFiles.Items.Any());

        Assert.IsFalse(this.FileMenu.Save.Items.Any()); // maybe this should throw, but up to you
    }
}

**Comment by thePantz** [comment]
Thanks for the reply! This looks great!
Although I think there is the need for an INamedClickablePageModel for cases where we need to evaluate the name of Buttons, MenuItems, TabPages and other clickable ui with display text
